namespace Starshine.Abp.PermissionManagement.EntityFrameworkCore;

public class PermissionGrantRepository_Tests : PermissionGrantRepository_Tests<AbpPermissionManagementEntityFrameworkCoreTestModule>
{

}
